<?php 
 $path = 'GUA_options/Settings/TrackingID';
 $trackingId = Mage::getStoreConfig($path);
 
 $path = 'GUA_options/Settings/Domain';
 $domain = Mage::getStoreConfig($path);
 
 if( !empty( $trackingId ) && !empty( $domain ) ){
?>
<!--start of Google Universal Analytics js code-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', '<?php echo $trackingId; ?>', '<?php echo $domain; ?>');
  ga('send', 'pageview');
</script>
<!--end of Google Universal Analytics js code-->
 <?php } ?>